### PR TITLE
test: add test for passing large document to zaakbrug

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
Presently the last test about a big document fails. Jaco thinks this can be fixed by changing the nginx configuration.

**Comment by mhdirkse** [comment]
I ran the tests while circumventing nginx - access ZaakBrug directly. The request with the large document was sent but no answer came back as I could see in SoapUI. No Ladybug report.

**Comment by mhdirkse** [comment]
Same result when I access ZaakBrug via nginx. The test with the big request takes a long time. There is no answer for the request that does voegZaakdocumentToe. This time I checked for the raw output (I forgot to check that when circumventing ZaakBrug - there may have been an answer but I do not expect so).

**Comment by mhdirkse** [comment]
This time there is a Ladybug report for the voegZaakdocumentToe. Here is a screenshot:

image

**Review by MLenterman — APPROVED** [review]

**Pull request merged**
